### ISSUE TITLE
Break startup of IntelliJ IDEA 2023.3 and its families

### ISSUE THREAD

**Issue by miurahr** [batya239/NyanProgressBar#9]
Because a failure is too early before initialize UI component, there is no informative log or message. 

```
Your JRE: 17.0.9+7-b1087.9 amd64 (JetBrains s.r.o.)
/home/miurahr/.local/share/JetBrains/Toolbox/apps/intellij-idea-ultimate-3/jbr
java.lang.Error: no ComponentUI class for: javax.swing.JTextPane[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=,minimumSize=,preferredSize=,caretColor=,disabledTextColor=,editable=true,margin=,selectedTextColor=,selectionColor=,kit=,typeHandlers=]
	at java.desktop/javax.swing.UIDefaults.getUIError(UIDefaults.java:763)
	at java.desktop/javax.swing.MultiUIDefaults.getUIError(MultiUIDefaults.java:146)
	at java.desktop/javax.swing.UIDefaults.getUI(UIDefaults.java:793)
	at java.desktop/javax.swing.UIManager.getUI(UIManager.java:1078)
	at java.desktop/javax.swing.text.JTextComponent.updateUI(JTextComponent.java:352)
	at java.desktop/javax.swing.text.JTextComponent.<init>(JTextComponent.java:326)
	at java.desktop/javax.swing.JEditorPane.<init>(JEditorPane.java:254)
	at java.desktop/javax.swing.JTextPane.<init>(JTextPane.java:100)
	at com.intellij.platform.ide.bootstrap.StartupErrorReporter.showMessage(StartupErrorReporter.java:111)
	at com.intellij.platform.ide.bootstrap.StartupErrorReporter.showMessage(StartupErrorReporter.java:61)
	at com.intellij.idea.Main.mainImpl(Main.kt:77)
	at com.intellij.idea.Main.mainImpl$default(Main.kt:49)
	at com.intellij.idea.Main.main(Main.kt:46)

Also, a UI exception occurred on an attempt to show the above message
java.lang.NullPointerException: Cannot invoke "javax.swing.text.Caret.setDot(int)" because "this.caret" is null
	at java.desktop/javax.swing.text.JTextComponent.setCaretPosition(JTextComponent.java:1691)
	at com.intellij.platform.ide.bootstrap.StartupErrorReporter.showMessage(StartupErrorReporter.java:115)
	at com.intellij.platform.ide.bootstrap.StartupErrorReporter.showMessage(StartupErrorReporter.java:61)
	at com.intellij.idea.Main.mainImpl(Main.kt:77)
	at com.intellij.idea.Main.mainImpl$default(Main.kt:49)
	at com.intellij.idea.Main.main(Main.kt:46)
```

**Comment by jsvetl47-cell** [comment]
https://github.com/batya239/NyanProgressBar/issues/9

**Comment by jsvetl47-cell** [comment]
> Protože k selhání dochází příliš brzy před inicializací komponenty uživatelského rozhraní, neexistuje žádný informativní protokol ani zpráva.
> 
> ```
> Your JRE: 17.0.9+7-b1087.9 amd64 (JetBrains s.r.o.)
> /home/miurahr/.local/share/JetBrains/Toolbox/apps/intellij-idea-ultimate-3/jbr
> java.lang.Error: no ComponentUI class for: javax.swing.JTextPane[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=,minimumSize=,preferredSize=,caretColor=,disabledTextColor=,editable=true,margin=,selectedTextColor=,selectionColor=,kit=,typeHandlers=]
> 	at java.desktop/javax.swing.UIDefaults.getUIError(UIDefaults.java:763)
> 	at java.desktop/javax.swing.MultiUIDefaults.getUIError(MultiUIDefaults.java:146)
> 	at java.desktop/javax.swing.UIDefaults.getUI(UIDefaults.java:793)
> 	at java.desktop/javax.swing.UIManager.getUI(UIManager.java:1078)
> 	at java.desktop/javax.swing.text.JTextComponent.updateUI(JTextComponent.java:352)
> 	at java.desktop/javax.swing.text.JTextComponent.<init>(JTextComponent.java:326)
> 	at java.desktop/javax.swing.JEditorPane.<init>(JEditorPane.java:254)
> 	at java.desktop/javax.swing.JTextPane.<init>(JTextPane.java:100)
> 	at com.intellij.platform.ide.bootstrap.StartupErrorReporter.showMessage(StartupErrorReporter.java:111)
> 	at com.intellij.platform.ide.bootstrap.StartupErrorReporter.showMessage(StartupErrorReporter.java:61)
> 	at com.intellij.idea.Main.mainImpl(Main.kt:77)
> 	at com.intellij.idea.Main.mainImpl$default(Main.kt:49)
> 	at com.intellij.idea.Main.main(Main.kt:46)
> 
> Also, a UI exception occurred on an attempt to show the above message
> java.lang.NullPointerException: Cannot invoke "javax.swing.text.Caret.setDot(int)" because "this.caret" is null
> 	at java.desktop/javax.swing.text.JTextComponent.setCaretPosition(JTextComponent.java:1691)
> 	at com.intellij.platform.ide.bootstrap.StartupErrorReporter.showMessage(StartupErrorReporter.java:115)
> 	at com.intellij.platform.ide.bootstrap.StartupErrorReporter.showMessage(StartupErrorReporter.java:61)
> 	at com.intellij.idea.Main.mainImpl(Main.kt:77)
> 	at com.intellij.idea.Main.mainImpl$default(Main.kt:49)
> 	at com.intellij.idea.Main.main(Main.kt:46)
> ```
